language: objective-c
osx_image: xcode8
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild -version
  - xcodebuild -workspace Bulldog.xcworkspace -scheme Bulldog -destination 'platform=iOS Simulator,name=iPhone 7' build test | xcpretty;
  - pod lib lint;
