language: objective-c  #1
osx_image: xcode8.0 #2
env:
  global:
    - WORKSPACE=Bulldog.xcworkspace
    - SCHEME=Bulldog
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" build test | xcpretty;

pod lib lint;
